version: '3.9'
services:
  serviceregistry:
    container_name: serviceregistry
    networks:
      - harrynetwork
    build:
      context: ./service-registry
      dockerfile: Dockerfile
    ports:
      - 8761:8761
    environment:
      EUREKA_CLIENT_SERVICEURL_DEFAULTZONE: http://serviceregistry:8761/eureka
      SPRING_CLOUD_CONFIG_SERVER_GIT_URI: https://github.com/vijayam1030/config-server
      SPRING_CLOUD_CONFIG_URI: http://configserver:9296
      SPRING_ZIPKIN_BASE-URL: http://zipkinserver:9411/


  configserver:
    container_name: configserver
    networks:
      - harrynetwork
    build:
      context: ./cloud-config-server
      dockerfile: Dockerfile
    ports:
      - 9296:9296
    environment:
      EUREKA_CLIENT_SERVICEURL_DEFAULTZONE: http://serviceregistry:8761/eureka
      SPRING_CLOUD_CONFIG_SERVER_GIT_URI: https://github.com/vijayam1030/config-server
      SPRING_CLOUD_CONFIG_URI: http://configserver:9296
      SPRING_ZIPKIN_BASE-URL: http://zipkinserver:9411/


  cloudgateway:
    container_name: cloudgateway
    networks:
      - harrynetwork
    build:
      context: ./cloud-gateway
      dockerfile: Dockerfile
    ports:
      - 9191:9191
    environment:
      EUREKA_CLIENT_SERVICEURL_DEFAULTZONE: http://serviceregistry:8761/eureka
      SPRING_CLOUD_CONFIG_SERVER_GIT_URI: https://github.com/vijayam1030/config-server
      SPRING_CLOUD_CONFIG_URI: http://configserver:9296
      SPRING_ZIPKIN_BASE-URL: http://zipkinserver:9411/


  zipkinserver:
    container_name: zipkinserver
    networks:
      - harrynetwork
    build:
      context: ./zipkin-server2
      dockerfile: Dockerfile
    ports:
      - 9411:9411
    environment:
      EUREKA_CLIENT_SERVICEURL_DEFAULTZONE: http://serviceregistry:8761/eureka
      SPRING_CLOUD_CONFIG_SERVER_GIT_URI: https://github.com/vijayam1030/config-server
      SPRING_CLOUD_CONFIG_URI: http://configserver:9296
      SPRING_ZIPKIN_BASE-URL: http://zipkinserver:9411/


  userservice:
    container_name: userservice
    networks:
      - harrynetwork
    build:
      context: ./user-service
      dockerfile: Dockerfile
    ports:
      - 9002:9002
    environment:
      EUREKA_CLIENT_SERVICEURL_DEFAULTZONE: http://serviceregistry:8761/eureka
      SPRING_CLOUD_CONFIG_SERVER_GIT_URI: https://github.com/vijayam1030/config-server
      SPRING_CLOUD_CONFIG_URI: http://configserver:9296
      SPRING_ZIPKIN_BASE-URL: http://zipkinserver:9411/


  department:
    container_name: departmentservice
    networks:
      - harrynetwork
    build:
      context: ./department-service
      dockerfile: Dockerfile
    ports:
      - 9001:9001
    environment:
      EUREKA_CLIENT_SERVICEURL_DEFAULTZONE: http://serviceregistry:8761/eureka
      SPRING_CLOUD_CONFIG_SERVER_GIT_URI: https://github.com/vijayam1030/config-server
      SPRING_CLOUD_CONFIG_URI: http://configserver:9296
      SPRING_ZIPKIN_BASE-URL: http://zipkinserver:9411/

      
networks:
  harrynetwork:
    external: true

