server:
  port: 9191

spring:
  application:
    name: API-GATEWAY



  cloud:
    gateway:
      routes:
      - id: USER-SERVICE
        uri: lb://USER-SERVICE
        predicates:
          - Path=/users/**
      - id: DEPARTMENT-SERVICE
        uri: lb://DEPARTMENT-SERVICE
        predicates:
          - Path=/departments/**
#      - id: FALLBACK-SERVICE
#        uri: lb://FALLBACK-SERVICE
#        predicates:
#          - Path=/departments/**


eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://serviceregistry:8761/eureka/
  instance:
    hostname: serviceregistry

